version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: insurance_underwriting
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - db

volumes:
  postgres_data: